
unix_file : pthread_linux.c
	gcc -o UNIX_File pthread_linux.c -Wall -pthread

create_thread : creation_of_threads.c
	gcc -o create_thread creation_of_threads.c -Wall -pthread
	
sig_handling : signal_handling_in_C_program.c
	gcc -o sig_handing signal_handling_in_C_program.c