
fork : fork_system_call.o
	gcc -o fork fork_system_call.o
	
fork_system_call.o : fork_system_call.c
	gcc -c fork_system_call.c
	
fork_test_1 : fork_test_1.c
	gcc -g -o fork_test_1 fork_test_1.c

fork_test_2 : fork_test_2.c
	gcc -c fork_test_2 fork_test_2.c